// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blog.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blog struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Keywords             int32    `protobuf:"varint,3,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Blog) GetKeywords() int32 {
	if m != nil {
		return m.Keywords
	}
	return 0
}

func (m *Blog) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type GetBlogListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlogListRequest) Reset()         { *m = GetBlogListRequest{} }
func (m *GetBlogListRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlogListRequest) ProtoMessage()    {}
func (*GetBlogListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{1}
}

func (m *GetBlogListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlogListRequest.Unmarshal(m, b)
}
func (m *GetBlogListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlogListRequest.Marshal(b, m, deterministic)
}
func (m *GetBlogListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlogListRequest.Merge(m, src)
}
func (m *GetBlogListRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlogListRequest.Size(m)
}
func (m *GetBlogListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlogListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlogListRequest proto.InternalMessageInfo

type GetBlogListResponse struct {
	Blogs                []*Blog  `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlogListResponse) Reset()         { *m = GetBlogListResponse{} }
func (m *GetBlogListResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlogListResponse) ProtoMessage()    {}
func (*GetBlogListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{2}
}

func (m *GetBlogListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlogListResponse.Unmarshal(m, b)
}
func (m *GetBlogListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlogListResponse.Marshal(b, m, deterministic)
}
func (m *GetBlogListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlogListResponse.Merge(m, src)
}
func (m *GetBlogListResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlogListResponse.Size(m)
}
func (m *GetBlogListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlogListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlogListResponse proto.InternalMessageInfo

func (m *GetBlogListResponse) GetBlogs() []*Blog {
	if m != nil {
		return m.Blogs
	}
	return nil
}

func init() {
	proto.RegisterType((*Blog)(nil), "Blog")
	proto.RegisterType((*GetBlogListRequest)(nil), "GetBlogListRequest")
	proto.RegisterType((*GetBlogListResponse)(nil), "GetBlogListResponse")
}

func init() { proto.RegisterFile("proto/blog.proto", fileDescriptor_fc5203cdc85000bc) }

var fileDescriptor_fc5203cdc85000bc = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4f, 0xc4, 0x30,
	0x0c, 0x85, 0x09, 0xd7, 0x9c, 0x38, 0x77, 0x41, 0xbe, 0x0a, 0x45, 0xc7, 0x52, 0x65, 0xea, 0x94,
	0x93, 0xca, 0xc6, 0x58, 0x06, 0x16, 0xa6, 0x8c, 0x6c, 0x54, 0xb5, 0x4a, 0x45, 0x44, 0x4a, 0x9c,
	0x82, 0xf8, 0xf7, 0x28, 0x29, 0x42, 0x20, 0x6e, 0x7b, 0xdf, 0x93, 0x9f, 0x9f, 0x65, 0xb8, 0x9c,
	0x83, 0x8f, 0xfe, 0xd8, 0x3b, 0x3f, 0x9a, 0x2c, 0xf5, 0x00, 0x45, 0xe7, 0xfc, 0x88, 0x15, 0xc8,
	0x38, 0x45, 0x47, 0x4a, 0xd4, 0xa2, 0xd9, 0xd9, 0x15, 0x10, 0xa1, 0x60, 0xb7, 0x8c, 0xea, 0x3c,
	0x9b, 0x59, 0xe3, 0x01, 0x2e, 0x5e, 0xe8, 0xf3, 0xc3, 0x87, 0x81, 0xd5, 0xa6, 0x16, 0x8d, 0xb4,
	0x3f, 0x8c, 0x57, 0xb0, 0x7d, 0x5a, 0xe2, 0xb3, 0x0f, 0xaa, 0xc8, 0x89, 0x6f, 0xd2, 0x15, 0xe0,
	0x3d, 0xc5, 0x54, 0xf4, 0x30, 0x71, 0xb4, 0xf4, 0xb6, 0x10, 0x47, 0xdd, 0xc2, 0xfe, 0x8f, 0xcb,
	0xb3, 0x7f, 0x65, 0xc2, 0x6b, 0x90, 0xe9, 0x40, 0x56, 0xa2, 0xde, 0x34, 0x65, 0x2b, 0x4d, 0x9a,
	0xb0, 0xab, 0xd7, 0xde, 0x81, 0x4c, 0xc8, 0x78, 0x0b, 0xe5, 0xaf, 0x30, 0xee, 0xcd, 0xff, 0x82,
	0x43, 0x65, 0x4e, 0xec, 0xd7, 0x67, 0x5d, 0xf9, 0xb8, 0x63, 0x0a, 0xef, 0x14, 0x8e, 0x73, 0xdf,
	0x6f, 0xf3, 0x23, 0x6e, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x11, 0x43, 0xd3, 0x1c, 0x01,
	0x00, 0x00,
}
